"""Runtime Korean/English string catalog with QSettings persistence."""

from __future__ import annotations

from PySide6.QtCore import QObject, QLocale, QSettings, Signal


EN = {
    "menu.file": "File", "menu.edit": "Edit", "menu.layer": "Layer",
    "menu.frame": "Frame", "menu.animation": "Animation", "menu.view": "View",
    "menu.export": "Export", "menu.settings": "Settings", "menu.language": "Language",
    "language.ko": "한국어", "language.en": "English",
    "action.new_project": "New Project…", "action.open": "Open…",
    "action.save": "Save", "action.save_as": "Save As…",
    "action.exit": "Exit",
    "action.project_settings": "Project Settings…",
    "action.import_source": "Import Source Asset…",
    "action.playback_test": "Create Playback Test Project",
    "action.export_frames": "Export PNG Frames…",
    "action.keyboard_shortcuts": "Keyboard Shortcuts…",
    "action.new_layer": "New Layer", "action.delete_layer": "Delete Layer",
    "action.new_frame": "New Frame (Duplicate Current)",
    "action.new_empty_frame": "New Empty Frame", "action.delete_frame": "Delete Frame",
    "action.play_stop": "Play / Stop Animation", "action.status_bar": "Status Bar",
    "effects.library.title": "Effect Library", "effects.sources": "Source Assets",
    "effects.generators": "Generators", "effects.import": "Import Source Asset…",
    "effects.add_emitter": "Add Transform Emitter", "effects.delete_source": "Delete Source",
    "effects.delete_generator": "Delete Generator", "effects.no_source": "No source selected",
    "effects.properties.title": "Effect Properties",
    "effects.select_emitter": "Select a Transform Emitter",
    "effects.auto_preview": "Auto Preview", "effects.refresh_preview": "Refresh Preview",
    "effects.apply_to_frames": "Apply to Frames", "effects.revert": "Revert Changes",
    "effects.reset_defaults": "Reset to Defaults", "effects.applied_frames": "Applied Frames",
    "effects.live_preview": "Live Preview — Unapplied",
    "state.applied": "Applied", "state.settings_changed": "Settings changed",
    "state.updating": "Updating preview... Showing previous result.",
    "state.ready": "Preview ready — Not applied",
    "state.failed": "Preview failed. Applied frames were not changed.",
    "play.playing": "Playing", "play.stopped": "Stopped",
    "play.preview_playing": "Preview Playing", "play.preview_stopped": "Preview Stopped",
    "play.frame": "Frame", "play.fps": "FPS",
    "shortcut.new_layer": "New Layer", "shortcut.new_frame": "New Frame",
    "shortcut.undo": "Undo", "shortcut.redo": "Redo",
    "shortcut.new_empty_frame": "New Empty Frame",
    "shortcut.play_stop_animation": "Play / Stop Animation",
    "shortcut.previous_frame": "Previous Frame", "shortcut.next_frame": "Next Frame",
    "shortcut.primary": "Primary", "shortcut.alternate": "Alternate",
    "shortcut.title": "Keyboard Shortcuts", "shortcut.restore": "Restore Defaults",
    "shortcut.apply": "Apply",
    "message.unapplied": "This generator has unapplied preview changes.",
    "message.saved_without_preview": "The project was saved without unapplied preview changes.",
    "message.export_without_preview": "Unapplied preview changes are not included in the export.",
    "effects.preview_badge": "PREVIEW",
    "section.source": "Source", "section.timing": "Timing", "section.distribution": "Distribution",
    "section.motion": "Motion", "section.transform": "Transform", "section.pseudo3d": "Pseudo 3D",
    "section.opacity": "Opacity", "section.easing": "Easing",
    "field.source_asset": "Source Asset", "field.output_frames": "Output Frames",
    "field.instance_count": "Instance Count", "field.start_frame": "Start Frame",
    "field.emission_interval": "Emission Interval", "field.lifetime": "Lifetime",
    "field.type": "Type", "field.origin_x": "Origin X", "field.origin_y": "Origin Y",
    "field.line_end_x": "Line End X", "field.line_end_y": "Line End Y",
    "field.radius": "Radius", "field.start_angle": "Start Angle", "field.end_angle": "End Angle",
    "field.position_x": "Position X", "field.position_y": "Position Y",
    "field.rotation": "Rotation", "field.scale_x": "Scale X", "field.scale_y": "Scale Y",
    "field.horizontal_tilt": "Horizontal Tilt", "field.vertical_tilt": "Vertical Tilt",
    "field.perspective": "Perspective", "field.opacity": "Opacity", "field.curve": "Curve",
    "distribution.point": "Point", "distribution.line": "Line", "distribution.circle": "Circle",
    "easing.linear": "Linear", "easing.ease_in": "Ease In", "easing.ease_out": "Ease Out",
    "timeline.add_frame": "+ Frame", "timeline.duplicate_frame": "⧉ Frame",
    "timeline.delete_frame": "− Frame", "timeline.add_layer": "+ Layer",
    "timeline.delete_layer": "− Layer",
    "dialog.new_project": "New Project", "dialog.project_settings": "Project Settings",
    "dialog.project_name": "Project name", "dialog.canvas_preset": "Canvas preset",
    "dialog.canvas_width": "Canvas width", "dialog.canvas_height": "Canvas height",
    "dialog.playback_speed": "Playback speed", "dialog.loop": "Loop animation",
    "dialog.create": "Create", "dialog.custom": "Custom", "dialog.enter_name": "Enter a project name.",
    "dialog.general": "General", "dialog.canvas": "Canvas", "dialog.anchor": "Anchor",
    "dialog.current_size": "Current Size", "dialog.new_width": "New Width",
    "dialog.new_height": "New Height", "dialog.canvas_only": "Resize canvas only",
    "dialog.scale_canvas": "Scale image and canvas",
    "gizmo.move": "Move", "gizmo.rotate": "Rotate", "gizmo.scale": "Scale",
    "gizmo.distribution": "Distribution", "gizmo.edit_end": "Edit End",
    "gizmo.tooltip.move": "Drag to move the selected draft on integer canvas pixels.",
    "gizmo.tooltip.rotate": "Drag the rotation handle; hold Shift to snap by 15°.",
    "gizmo.tooltip.scale": "Drag to change positive X/Y scale.",
    "gizmo.tooltip.distribution": "Edit Point, Line, or Circle distribution handles.",
    "effects.clip_generators": "Clip Generators", "effects.legacy_clip_generators": "Legacy Clip Generators", "effects.animation_clips": "Animation Clips",
    "effects.particle_emitters": "Particle Emitters", "effects.create_clip": "Create Animation Clip",
    "effects.update_clip": "Update Animation Clip", "effects.add_particle": "Add Particle Emitter",
    "effects.bake": "Bake to Frames", "effects.export_preview": "Export Preview Sequence…",
    "particle.burst": "Burst", "particle.over_time": "Over Time", "particle.spawn_shape": "Spawn Shape",
    "particle.fixed": "Fixed Direction", "particle.radial": "Radial Outward",
    "particle.randomize_seed": "Randomize Seed", "particle.clip_playback": "Clip Playback",
    "particle.resource":"Particle Resource", "particle.resource_compositions":"Resource Compositions",
    "workspace.effect":"Effect Editor","workspace.resource":"Resource Editor",
    "resource.library":"Resource Library","resource.details":"Resource Details","resource.import":"Import Resources…",
    "resource.empty":"No resources.\nDrop PNG, GIF, or Aseprite files here.","resource.center_pivot":"Center Pivot",
    "resource.reimport":"Reimport Resource","resource.delete":"Delete Resource","resource.create_emitter":"Create Particle Emitter from Resource",
    "resource.import_summary":"{success} resources imported. {failed} files could not be imported.",
    "resource.preview_invalidated":"Resource changed. Preview again before baking.","resource.in_use":"This resource is currently in use and cannot be deleted.","resource.delete_confirm":"Delete this embedded resource?",
    "external.title":"External Tools…","external.browse":"Browse…","external.detect":"Auto Detect","external.validate":"Validate","external.clear":"Clear",
    "external.valid":"Valid","external.invalid":"Invalid","external.not_found":"Not Found",
    "resource.static":"Static Resources","resource.animated":"Animated Resources","resource.frame":"Frame","resource.drop":"Drop PNG, GIF, or Aseprite files here","resource.pivot_x":"Pivot X","resource.pivot_y":"Pivot Y","resource.loop":"Loop",
    "composition.assets":"Assets", "composition.compositions":"Compositions", "composition.new":"New Resource Composition…",
    "composition.add_asset":"Add to Composition", "composition.delete":"Delete Composition", "composition.properties":"Layer Properties",
    "composition.add_property":"+ Add Property", "composition.full_rotation":"Add Full Rotation", "composition.pivot":"Pivot",
    "composition.name":"Name", "composition.width":"Width", "composition.height":"Height", "composition.fps":"FPS",
    "composition.duration":"Duration (seconds)", "composition.frames":"Frames", "composition.loop":"Loop",
    "startup.title":"Pixel Effect Maker — New Project", "startup.create":"Create Project", "startup.open":"Open Project…", "startup.initial_frames":"Initial Frames",
    "resource.start_text":"Import a PNG, GIF, or Aseprite asset, or create an empty resource.", "resource.start_import":"Import Asset", "resource.start_blank":"Create Empty Resource",
    "v2.length":"Length", "v2.frames":"Frames", "v2.seconds":"Seconds", "v2.length_frame_info":"{fps} FPS = {seconds:.4f} seconds", "v2.length_seconds_info":"{fps} FPS = {frames} frames",
    "composition.search":"Search properties", "composition.add":"Add",
    "composition.start":"Layer Start", "composition.end":"Layer End", "composition.delete_keyframe":"Delete Keyframe",
    "composition.category.transform":"Transform", "composition.category.appearance":"Appearance",
    "composition.in_use":"This composition is used by a Particle Emitter.", "composition.delete_confirm":"Delete this Resource Composition?",
    "composition.remove_property_confirm":"Remove this property and all of its keyframes?",
    "composition.frame_status":"Frame {current} / {total} · {fps} FPS",
    "composition.tooltip.add_asset":"Adds the selected imported asset as a layer in the open composition.",
    "composition.tooltip.add_property":"Search and register only the animation property this layer needs.",
    "composition.tooltip.full_rotation":"Creates Linear 0° and 360° keyframes across the full composition.",
    "v2.assets":"Assets", "v2.resources":"Resources", "v2.empty":"Import an asset, then select it to create a resource.",
    "v2.asset_inspector":"Asset Inspector", "v2.composition_inspector":"Resource Inspector", "v2.layer_inspector":"Layer Inspector",
    "v2.asset_pivot_x":"Asset Pivot X", "v2.asset_pivot_y":"Asset Pivot Y", "v2.center_asset_pivot":"Center Asset Pivot",
    "v2.create_from_asset":"Create Resource from This Asset", "v2.create_from_asset_tip":"Creates a ready-to-animate resource at the original asset size.",
    "v2.create_resource_title":"Create New Resource", "v2.create":"Create", "v2.cancel":"Cancel",
    "v2.output_pivot_x":"Output Pivot X", "v2.output_pivot_y":"Output Pivot Y", "v2.center_output_pivot":"Center Output Pivot",
    "v2.use_in_effect":"Use This Resource in Effect", "v2.use_in_effect_tip":"Creates a Particle Emitter that plays this resource and opens the Effect Editor.",
    "v2.layer_name":"Layer Name", "v2.source_asset":"Source Asset", "v2.visible":"Visible", "v2.layer_pivot_x":"Layer Pivot X", "v2.layer_pivot_y":"Layer Pivot Y", "v2.center_layer_pivot":"Center Layer Pivot",
    "v2.full_rotation":"Full Rotation", "v2.replace_rotation_confirm":"Replace the existing Rotation keyframes with a full 0° to 360° rotation?",
    "v2.loop":"Loop", "v2.hold":"Hold", "v2.comp_info":"{width} × {height} · {fps} FPS · {frames} frames · {playback}",
    "v2.delete_asset":"Delete Asset", "v2.delete_resource":"Delete Resource", "v2.delete":"Delete", "v2.replace":"Replace",
    "property.position":"Position", "property.rotation":"Rotation", "property.scale":"Scale", "property.opacity":"Opacity", "property.value":"Value", "property.x":"X", "property.y":"Y", "property.easing":"Easing", "property.remove":"Remove Property", "composition.add_keyframe":"Add Keyframe", "easing.ease_in_out":"Ease In/Out",
}

KO = {
    "menu.file": "파일", "menu.edit": "편집", "menu.layer": "레이어",
    "menu.frame": "프레임", "menu.animation": "애니메이션", "menu.view": "보기",
    "menu.export": "내보내기", "menu.settings": "설정", "menu.language": "언어",
    "language.ko": "한국어", "language.en": "English",
    "action.new_project": "새 프로젝트…", "action.open": "열기…",
    "action.save": "저장", "action.save_as": "다른 이름으로 저장…",
    "action.exit": "종료",
    "action.project_settings": "프로젝트 설정…",
    "action.import_source": "소스 에셋 가져오기…",
    "action.playback_test": "재생 테스트 프로젝트 만들기",
    "action.export_frames": "PNG 프레임 내보내기…",
    "action.keyboard_shortcuts": "키보드 단축키…",
    "action.new_layer": "새 레이어", "action.delete_layer": "레이어 삭제",
    "action.new_frame": "새 프레임(현재 프레임 복제)",
    "action.new_empty_frame": "새 빈 프레임", "action.delete_frame": "프레임 삭제",
    "action.play_stop": "애니메이션 재생 / 정지", "action.status_bar": "상태 표시줄",
    "effects.library.title": "이펙트 라이브러리", "effects.sources": "소스 에셋",
    "effects.generators": "생성기", "effects.import": "소스 에셋 가져오기…",
    "effects.add_emitter": "Transform Emitter 추가", "effects.delete_source": "소스 삭제",
    "effects.delete_generator": "생성기 삭제", "effects.no_source": "선택한 소스 없음",
    "effects.properties.title": "이펙트 속성",
    "effects.select_emitter": "Transform Emitter를 선택하세요",
    "effects.auto_preview": "자동 미리보기", "effects.refresh_preview": "미리보기 새로고침",
    "effects.apply_to_frames": "프레임에 적용", "effects.revert": "변경 되돌리기",
    "effects.reset_defaults": "기본값으로 초기화", "effects.applied_frames": "적용된 프레임",
    "effects.live_preview": "실시간 미리보기 — 미적용",
    "state.applied": "적용됨", "state.settings_changed": "설정 변경됨",
    "state.updating": "미리보기 갱신 중... 이전 결과를 표시합니다.",
    "state.ready": "미리보기 준비됨 — 미적용",
    "state.failed": "미리보기에 실패했습니다. 적용된 프레임은 변경되지 않았습니다.",
    "play.playing": "재생", "play.stopped": "정지",
    "play.preview_playing": "미리보기 재생", "play.preview_stopped": "미리보기 정지",
    "play.frame": "프레임", "play.fps": "FPS",
    "shortcut.new_layer": "새 레이어", "shortcut.new_frame": "새 프레임",
    "shortcut.undo": "실행 취소", "shortcut.redo": "다시 실행",
    "shortcut.new_empty_frame": "새 빈 프레임",
    "shortcut.play_stop_animation": "재생 / 정지",
    "shortcut.previous_frame": "이전 프레임", "shortcut.next_frame": "다음 프레임",
    "shortcut.primary": "기본 키", "shortcut.alternate": "보조 키",
    "shortcut.title": "키보드 단축키", "shortcut.restore": "기본값 복원",
    "shortcut.apply": "적용",
    "message.unapplied": "이 생성기에 아직 적용하지 않은 미리보기 변경사항이 있습니다.",
    "message.saved_without_preview": "미적용 미리보기 변경사항을 제외하고 프로젝트를 저장했습니다.",
    "message.export_without_preview": "미적용 미리보기 변경사항은 내보내기에 포함되지 않습니다.",
    "effects.preview_badge": "미리보기",
    "section.source": "소스", "section.timing": "시간", "section.distribution": "배치",
    "section.motion": "이동", "section.transform": "변형", "section.pseudo3d": "가상 3D",
    "section.opacity": "투명도", "section.easing": "보간",
    "field.source_asset": "소스 에셋", "field.output_frames": "출력 프레임",
    "field.instance_count": "인스턴스 수", "field.start_frame": "시작 프레임",
    "field.emission_interval": "방출 간격", "field.lifetime": "수명",
    "field.type": "방식", "field.origin_x": "발생점 X", "field.origin_y": "발생점 Y",
    "field.line_end_x": "선 끝 X", "field.line_end_y": "선 끝 Y",
    "field.radius": "반지름", "field.start_angle": "시작 각도", "field.end_angle": "끝 각도",
    "field.position_x": "위치 X", "field.position_y": "위치 Y",
    "field.rotation": "회전", "field.scale_x": "크기 X", "field.scale_y": "크기 Y",
    "field.horizontal_tilt": "수평 기울기", "field.vertical_tilt": "수직 기울기",
    "field.perspective": "원근감", "field.opacity": "불투명도", "field.curve": "곡선",
    "distribution.point": "점", "distribution.line": "선", "distribution.circle": "원",
    "easing.linear": "선형", "easing.ease_in": "가속", "easing.ease_out": "감속",
    "timeline.add_frame": "+ 프레임", "timeline.duplicate_frame": "⧉ 프레임",
    "timeline.delete_frame": "− 프레임", "timeline.add_layer": "+ 레이어",
    "timeline.delete_layer": "− 레이어",
    "dialog.new_project": "새 프로젝트", "dialog.project_settings": "프로젝트 설정",
    "dialog.project_name": "프로젝트 이름", "dialog.canvas_preset": "캔버스 프리셋",
    "dialog.canvas_width": "캔버스 너비", "dialog.canvas_height": "캔버스 높이",
    "dialog.playback_speed": "재생 속도", "dialog.loop": "애니메이션 반복",
    "dialog.create": "만들기", "dialog.custom": "사용자 지정", "dialog.enter_name": "프로젝트 이름을 입력하세요.",
    "dialog.general": "일반", "dialog.canvas": "캔버스", "dialog.anchor": "기준점",
    "dialog.current_size": "현재 크기", "dialog.new_width": "새 너비",
    "dialog.new_height": "새 높이", "dialog.canvas_only": "캔버스만 크기 변경",
    "dialog.scale_canvas": "이미지와 캔버스 크기 변경",
    "gizmo.move": "이동", "gizmo.rotate": "회전", "gizmo.scale": "크기",
    "gizmo.distribution": "배치", "gizmo.edit_end": "끝 상태 편집",
    "gizmo.tooltip.move": "선택한 Draft를 캔버스 정수 픽셀 단위로 이동합니다.",
    "gizmo.tooltip.rotate": "회전 핸들을 드래그합니다. Shift를 누르면 15° 단위로 맞춥니다.",
    "gizmo.tooltip.scale": "드래그해 양수 X/Y 크기를 변경합니다.",
    "gizmo.tooltip.distribution": "점, 선 또는 원 배치 핸들을 조절합니다.",
    "effects.clip_generators": "클립 생성기", "effects.legacy_clip_generators": "Legacy 클립 생성기", "effects.animation_clips": "애니메이션 클립",
    "effects.particle_emitters": "파티클 방출기", "effects.create_clip": "애니메이션 클립 만들기",
    "effects.update_clip": "애니메이션 클립 업데이트", "effects.add_particle": "파티클 방출기 추가",
    "effects.bake": "프레임에 굽기", "effects.export_preview": "미리보기 시퀀스 내보내기…",
    "particle.burst": "일괄 방출", "particle.over_time": "시간 분산 방출", "particle.spawn_shape": "생성 형태",
    "particle.fixed": "지정 방향", "particle.radial": "바깥 방향",
    "particle.randomize_seed": "시드 무작위 변경", "particle.clip_playback": "클립 재생",
    "particle.resource":"파티클 리소스", "particle.resource_compositions":"리소스 컴포지션",
    "workspace.effect":"이펙트 에디터","workspace.resource":"리소스 에디터",
    "resource.library":"리소스 라이브러리","resource.details":"리소스 상세","resource.import":"리소스 가져오기…",
    "resource.empty":"리소스가 없습니다.\nPNG, GIF 또는 Aseprite 파일을 여기에 놓으세요.","resource.center_pivot":"피벗 중앙 정렬",
    "resource.reimport":"리소스 다시 가져오기","resource.delete":"리소스 삭제","resource.create_emitter":"이 리소스로 파티클 방출기 만들기",
    "resource.import_summary":"리소스 {success}개를 가져왔습니다. 파일 {failed}개를 가져오지 못했습니다.",
    "resource.preview_invalidated":"리소스가 변경됐습니다. 굽기 전에 다시 미리보기 하세요.","resource.in_use":"이 리소스는 사용 중이므로 삭제할 수 없습니다.","resource.delete_confirm":"이 내장 리소스를 삭제할까요?",
    "external.title":"외부 도구…","external.browse":"찾아보기…","external.detect":"자동 탐색","external.validate":"검증","external.clear":"지우기",
    "external.valid":"정상","external.invalid":"유효하지 않음","external.not_found":"찾을 수 없음",
    "resource.static":"정적 리소스","resource.animated":"애니메이션 리소스","resource.frame":"프레임","resource.drop":"PNG, GIF 또는 Aseprite 파일을 여기에 놓으세요","resource.pivot_x":"피벗 X","resource.pivot_y":"피벗 Y","resource.loop":"반복",
    "composition.assets":"에셋", "composition.compositions":"컴포지션", "composition.new":"새 리소스 컴포지션…",
    "composition.add_asset":"컴포지션에 추가", "composition.delete":"컴포지션 삭제", "composition.properties":"레이어 속성",
    "composition.add_property":"+ 속성 추가", "composition.full_rotation":"한 바퀴 회전 추가", "composition.pivot":"피벗",
    "composition.name":"이름", "composition.width":"너비", "composition.height":"높이", "composition.fps":"FPS",
    "composition.duration":"길이(초)", "composition.frames":"프레임", "composition.loop":"반복",
    "startup.title":"Pixel Effect Maker — 새 프로젝트", "startup.create":"새 프로젝트 시작", "startup.open":"프로젝트 열기…", "startup.initial_frames":"초기 프레임 수",
    "resource.start_text":"PNG, GIF 또는 Aseprite 에셋을 가져오거나 빈 리소스를 만들어 시작하세요.", "resource.start_import":"에셋 가져오기", "resource.start_blank":"빈 리소스 만들기",
    "v2.length":"길이", "v2.frames":"프레임", "v2.seconds":"초", "v2.length_frame_info":"{fps} FPS 기준 {seconds:.4f}초", "v2.length_seconds_info":"{fps} FPS 기준 {frames}프레임",
    "composition.search":"속성 검색", "composition.add":"추가",
    "composition.start":"레이어 시작", "composition.end":"레이어 끝", "composition.delete_keyframe":"키프레임 삭제",
    "composition.category.transform":"변형", "composition.category.appearance":"표시",
    "composition.in_use":"이 컴포지션은 파티클 방출기에서 사용 중입니다.", "composition.delete_confirm":"이 리소스 컴포지션을 삭제할까요?",
    "composition.remove_property_confirm":"이 속성과 모든 키프레임을 삭제할까요?",
    "composition.frame_status":"프레임 {current} / {total} · {fps} FPS",
    "composition.tooltip.add_asset":"선택한 원본 에셋을 열린 컴포지션의 레이어로 추가합니다.",
    "composition.tooltip.add_property":"이 레이어에 필요한 애니메이션 속성만 검색해 등록합니다.",
    "composition.tooltip.full_rotation":"컴포지션 전체 구간에 Linear 0°와 360° 키프레임을 만듭니다.",
    "v2.assets":"에셋", "v2.resources":"리소스", "v2.empty":"에셋을 가져온 뒤 선택해 리소스를 만드세요.",
    "v2.asset_inspector":"에셋 검사", "v2.composition_inspector":"리소스 정보", "v2.layer_inspector":"레이어 속성",
    "v2.asset_pivot_x":"에셋 피벗 X", "v2.asset_pivot_y":"에셋 피벗 Y", "v2.center_asset_pivot":"에셋 피벗 중앙 정렬",
    "v2.create_from_asset":"이 에셋으로 리소스 만들기", "v2.create_from_asset_tip":"원본 에셋 크기로 바로 애니메이션할 수 있는 리소스를 만듭니다.",
    "v2.create_resource_title":"새 리소스 만들기", "v2.create":"만들기", "v2.cancel":"취소",
    "v2.output_pivot_x":"출력 피벗 X", "v2.output_pivot_y":"출력 피벗 Y", "v2.center_output_pivot":"출력 피벗 중앙 정렬",
    "v2.use_in_effect":"이 리소스를 이펙트에서 사용", "v2.use_in_effect_tip":"이 리소스를 재생하는 파티클 방출기를 만들고 이펙트 에디터를 엽니다.",
    "v2.layer_name":"레이어 이름", "v2.source_asset":"원본 에셋", "v2.visible":"표시", "v2.layer_pivot_x":"레이어 피벗 X", "v2.layer_pivot_y":"레이어 피벗 Y", "v2.center_layer_pivot":"레이어 피벗 중앙 정렬",
    "v2.full_rotation":"한 바퀴 회전", "v2.replace_rotation_confirm":"기존 회전 키프레임을 0°에서 360°까지의 한 바퀴 회전으로 교체할까요?",
    "v2.loop":"반복", "v2.hold":"마지막 프레임 유지", "v2.comp_info":"{width} × {height} · {fps} FPS · {frames}프레임 · {playback}",
    "v2.delete_asset":"에셋 삭제", "v2.delete_resource":"리소스 삭제", "v2.delete":"삭제", "v2.replace":"교체",
    "property.position":"위치", "property.rotation":"회전", "property.scale":"크기", "property.opacity":"불투명도", "property.value":"값", "property.x":"X", "property.y":"Y", "property.easing":"보간", "property.remove":"속성 삭제", "composition.add_keyframe":"키프레임 추가", "easing.ease_in_out":"느리게 시작/종료",
}

EN.update({
    "action.undo":"Undo","action.redo":"Redo","action.undo_named":"Undo: {name}","action.redo_named":"Redo: {name}",
    "interface.title":"Interface Settings…","interface.timeline_frame_width":"Timeline Frame Width","interface.restore_default":"Restore Default",
    "tooltip.timeline_frame_width":"Changes the width of frame cells in every open timeline (20–96 px).",
    "tooltip.previous_frame":"Moves to the frame immediately before the current frame.","tooltip.next_frame":"Moves to the frame immediately after the current frame.",
    "tooltip.play_stop":"Plays or stops the current work at its configured FPS. Shortcut: Enter","tooltip.delete_keyframe":"Deletes the selected property keyframe at the current frame. This can be undone.",
    "tooltip.undo":"Undo the last application edit. Shortcut: Ctrl+Z","tooltip.redo":"Redo the last undone application edit. Shortcuts: Ctrl+Shift+Z / Ctrl+Y",
    "particle.title":"Particle Properties","particle.emission":"Emission","particle.direction":"Direction","particle.random_range":"Random Range",
    "particle.mode":"Mode","particle.count_min":"Count Min","particle.count_max":"Count Max","particle.duration":"Duration","particle.shape":"Shape",
    "particle.origin_x":"Origin X","particle.origin_y":"Origin Y","particle.line_end_x":"Line End X","particle.line_end_y":"Line End Y","particle.radius":"Radius","particle.box_width":"Box Width","particle.box_height":"Box Height",
    "particle.start_angle":"Start Angle","particle.end_angle":"End Angle","particle.direction_value":"Direction","particle.spread":"Spread","particle.speed_min":"Speed Min","particle.speed_max":"Speed Max",
    "particle.lifetime_min":"Lifetime Min","particle.lifetime_max":"Lifetime Max","particle.scale_min":"Scale Min","particle.scale_max":"Scale Max","particle.rotation_min":"Rotation Min","particle.rotation_max":"Rotation Max",
    "particle.angular_velocity_min":"Angular Velocity Min","particle.angular_velocity_max":"Angular Velocity Max","particle.start_delay_min":"Start Delay Min","particle.start_delay_max":"Start Delay Max","particle.clip_speed_min":"Clip Speed Min","particle.clip_speed_max":"Clip Speed Max",
    "particle.random_start_frame":"Random Start Frame","particle.opacity_start":"Opacity Start","particle.opacity_end":"Opacity End","particle.seed":"Seed","particle.output_frames":"Output Frames","particle.start_frame":"Start Frame","particle.resource_label":"Resource",
    "message.unsaved_title":"Unsaved Changes","message.discard_unsaved":"Discard the unsaved changes?","status.new_project":"New project created","status.opened":"Opened {path}","status.saved":"Saved {path}","status.imported":"Imported source asset: {name}","status.created":"Created {name}","status.generated":"Generated {name}","status.playback_test":"Playback test project created",
    "error.open":"Open Failed","error.save":"Save Failed","error.export":"Export Failed","error.import":"Import Failed","error.generation":"Generation Failed","error.canvas_resize":"Canvas Resize Failed","error.shortcuts":"Shortcut Settings","error.delete_frame":"Cannot Delete Frame","error.delete_layer":"Cannot Delete Layer",
})
KO.update({
    "action.undo":"실행 취소","action.redo":"다시 실행","action.undo_named":"실행 취소: {name}","action.redo_named":"다시 실행: {name}",
    "interface.title":"인터페이스 설정…","interface.timeline_frame_width":"타임라인 프레임 너비","interface.restore_default":"기본값 복원",
    "tooltip.timeline_frame_width":"열려 있는 모든 타임라인의 프레임 칸 너비를 20~96px 범위에서 변경합니다.",
    "tooltip.previous_frame":"현재 프레임의 바로 이전 프레임으로 이동합니다.","tooltip.next_frame":"현재 프레임의 바로 다음 프레임으로 이동합니다.",
    "tooltip.play_stop":"현재 작업을 설정된 FPS로 재생하거나 정지합니다. 단축키: Enter","tooltip.delete_keyframe":"현재 프레임에서 선택 속성의 키프레임을 삭제합니다. 실행 취소할 수 있습니다.",
    "tooltip.undo":"마지막 앱 편집을 취소합니다. 단축키: Ctrl+Z","tooltip.redo":"취소한 앱 편집을 다시 적용합니다. 단축키: Ctrl+Shift+Z / Ctrl+Y",
    "particle.title":"파티클 속성","particle.emission":"방출","particle.direction":"방향","particle.random_range":"무작위 범위",
    "particle.mode":"방식","particle.count_min":"최소 개수","particle.count_max":"최대 개수","particle.duration":"지속 시간","particle.shape":"형태",
    "particle.origin_x":"발생점 X","particle.origin_y":"발생점 Y","particle.line_end_x":"선 끝 X","particle.line_end_y":"선 끝 Y","particle.radius":"반지름","particle.box_width":"상자 너비","particle.box_height":"상자 높이",
    "particle.start_angle":"시작 각도","particle.end_angle":"끝 각도","particle.direction_value":"방향","particle.spread":"퍼짐 각도","particle.speed_min":"최소 속도","particle.speed_max":"최대 속도",
    "particle.lifetime_min":"최소 수명","particle.lifetime_max":"최대 수명","particle.scale_min":"최소 크기","particle.scale_max":"최대 크기","particle.rotation_min":"최소 회전","particle.rotation_max":"최대 회전",
    "particle.angular_velocity_min":"최소 회전 속도","particle.angular_velocity_max":"최대 회전 속도","particle.start_delay_min":"최소 시작 지연","particle.start_delay_max":"최대 시작 지연","particle.clip_speed_min":"최소 리소스 재생 속도","particle.clip_speed_max":"최대 리소스 재생 속도",
    "particle.random_start_frame":"시작 프레임 무작위","particle.opacity_start":"시작 불투명도","particle.opacity_end":"종료 불투명도","particle.seed":"시드","particle.output_frames":"출력 프레임","particle.start_frame":"시작 프레임","particle.resource_label":"리소스",
    "message.unsaved_title":"저장하지 않은 변경사항","message.discard_unsaved":"저장하지 않은 변경사항을 버릴까요?","status.new_project":"새 프로젝트를 만들었습니다","status.opened":"{path} 프로젝트를 열었습니다","status.saved":"{path} 프로젝트를 저장했습니다","status.imported":"소스 에셋을 가져왔습니다: {name}","status.created":"{name} 생성 완료","status.generated":"{name} 생성 완료","status.playback_test":"재생 테스트 프로젝트를 만들었습니다",
    "error.open":"열기 실패","error.save":"저장 실패","error.export":"내보내기 실패","error.import":"가져오기 실패","error.generation":"생성 실패","error.canvas_resize":"캔버스 크기 변경 실패","error.shortcuts":"단축키 설정","error.delete_frame":"프레임을 삭제할 수 없음","error.delete_layer":"레이어를 삭제할 수 없음",
})


class LocalizationService(QObject):
    language_changed = Signal(str)
    SETTINGS_KEY = "ui/language"

    def __init__(self, settings: QSettings, system_locale: str | None = None) -> None:
        super().__init__()
        self.settings = settings
        default = "ko" if (system_locale or QLocale.system().name()).lower().startswith("ko") else "en"
        saved = self.settings.value(self.SETTINGS_KEY, default, type=str)
        self.language = saved if saved in {"ko", "en"} else default

    def text(self, key: str, **values: object) -> str:
        catalog = KO if self.language == "ko" else EN
        template = catalog.get(key, EN.get(key, key))
        try:
            return template.format(**values)
        except (KeyError, ValueError):
            return template

    def set_language(self, language: str) -> None:
        if language not in {"ko", "en"}:
            language = "en"
        if language == self.language:
            return
        self.language = language
        self.settings.setValue(self.SETTINGS_KEY, language)
        self.settings.sync()
        self.language_changed.emit(language)
